In [ ]:
# Task 3: Data Cleaning and Preprocessing

## Objective

The objective of this project is to demonstrate professional data cleaning skills by transforming a deliberately messy employee dataset into a clean, analysis-ready dataset.

The cleaning process includes:
- Data quality assessment
- Missing value handling
- Duplicate removal
- Data standardisation
- Outlier detection
- Data type correction
- Before vs. after data quality comparison
- Exporting the cleaned dataset

## Technology Stack

- Python
- Pandas
- NumPy
- Jupyter Notebook

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv(r"C:\Users\soumy\OneDrive\Desktop\Task3-Datacleaning\Messy_Employee_dataset.csv")

In [9]:
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [10]:
df.shape

(1020, 12)

In [11]:
df.columns

Index(['Employee_ID', 'First_Name', 'Last_Name', 'Age', 'Department_Region',
       'Status', 'Join_Date', 'Salary', 'Email', 'Phone', 'Performance_Score',
       'Remote_Work'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   object
 7   Salary             996 non-null    float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(8)
memory usage: 88.8+ KB

In [13]:
before_rows = len(df)
before_columns = len(df.columns)
before_nulls = df.isnull().sum().sum()
before_duplicates = df.duplicated().sum()

print("Rows:", before_rows)
print("Columns:", before_columns)
print("Missing values:", before_nulls)
print("Duplicate rows:", before_duplicates)

Rows: 1020
Columns: 12
Missing values: 235
Duplicate rows: 0

In [ ]:
## 1. Data Quality Report

Before cleaning the dataset, a data quality assessment is performed to identify:
- Missing values
- Duplicate records
- Data types
- Unique values
- Potential data quality issues

In [15]:
quality_report = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str).values,
    "Missing Values": df.isnull().sum().values,
    "Unique Values": df.nunique().values
})

quality_report

               Column Data Type  Missing Values  Unique Values
0         Employee_ID    object               0           1020
1          First_Name    object               0              8
2           Last_Name    object               0              8
3                 Age   float64             211              4
4   Department_Region    object               0             36
5              Status    object               0              3
6           Join_Date    object               0            760
7              Salary   float64              24            978
8               Email    object               0             64
9               Phone     int64               0           1020
10  Performance_Score    object               0              4
11        Remote_Work      bool               0              2

In [16]:
df.isnull().sum()

Employee_ID            0
First_Name             0
Last_Name              0
Age                  211
Department_Region      0
Status                 0
Join_Date              0
Salary                24
Email                  0
Phone                  0
Performance_Score      0
Remote_Work            0
dtype: int64

In [17]:
missing_data = pd.DataFrame({
    "Column": df.columns,
    "Missing Values": df.isnull().sum().values
})

missing_data = missing_data[missing_data["Missing Values"] > 0]

missing_data

   Column  Missing Values
3     Age             211
7  Salary              24

In [18]:
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [19]:
df[df.duplicated()]

Empty DataFrame
Columns: [Employee_ID, First_Name, Last_Name, Age, Department_Region, Status, Join_Date, Salary, Email, Phone, Performance_Score, Remote_Work]
Index: []

In [20]:
df.dtypes

Employee_ID           object
First_Name            object
Last_Name             object
Age                  float64
Department_Region     object
Status                object
Join_Date             object
Salary               float64
Email                 object
Phone                  int64
Performance_Score     object
Remote_Work             bool
dtype: object

In [ ]:
## 2. Initial Data Quality Assessment

The dataset contains 1,020 employee records and 12 columns.

The initial inspection identified missing values in the `Age` and `Salary` columns. No exact duplicate rows were found. The `Join_Date` column is stored as an object and requires conversion to datetime. The `Phone` column is stored as an integer but should be treated as a string because phone numbers are identifiers rather than numerical values.

Further checks will be performed for inconsistent categorical values, invalid ranges, and numerical outliers.

In [21]:
# Initial dataset information

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("Total missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

Number of rows: 1020
Number of columns: 12
Total missing values: 235
Duplicate rows: 0

In [22]:
quality_report = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str),
    "Missing Values": df.isnull().sum(),
    "Unique Values": df.nunique()
})

quality_report

                              Column Data Type  Missing Values  Unique Values
Employee_ID              Employee_ID    object               0           1020
First_Name                First_Name    object               0              8
Last_Name                  Last_Name    object               0              8
Age                              Age   float64             211              4
Department_Region  Department_Region    object               0             36
Status                        Status    object               0              3
Join_Date                  Join_Date    object               0            760
Salary                        Salary   float64              24            978
Email                          Email    object               0             64
Phone                          Phone     int64               0           1020
Performance_Score  Performance_Score    object               0              4
Remote_Work              Remote_Work      bool               0              2

In [23]:
categorical_columns = [
    "Department_Region",
    "Status",
    "Performance_Score"
]

for col in categorical_columns:
    print("\n", col)
    print(df[col].value_counts(dropna=False))

 Department_Region
Department_Region
HR-Florida               41
DevOps-California        35
Sales-Nevada             35
Admin-Nevada             34
Admin-California         34
DevOps-Florida           34
Finance-Illinois         33
DevOps-New York          33
Sales-Florida            33
HR-New York              33
DevOps-Illinois          33
Finance-California       32
Sales-California         31
Sales-Illinois           30
Admin-Illinois           29
Finance-Texas            29
Cloud Tech-Texas         29
Cloud Tech-California    29
Finance-Nevada           29
Cloud Tech-Florida       28
DevOps-Nevada            27
DevOps-Texas             27
Sales-New York           26
HR-California            26
Admin-Florida            25
Cloud Tech-New York      24
Finance-Florida          24
HR-Illinois              24
HR-Nevada                24
HR-Texas                 23
Finance-New York         23
Sales-Texas              23
Admin-Texas              22
Admin-New York           22
Cloud Tech-Nevada        20
Cloud Tech-Illinois      16
Name: count, dtype: int64

 Status
Status
Pending     356
Active      352
Inactive    312
Name: count, dtype: int64

 Performance_Score
Performance_Score
Good         270
Average      267
Excellent    267
Poor         216
Name: count, dtype: int64

In [24]:
df[["Age", "Salary"]].describe()

              Age         Salary
count  809.000000     996.000000
mean    32.484549   85155.056396
std      5.656860   19873.727918
min     25.000000   50047.320000
25%     25.000000   68392.487500
50%     30.000000   85547.870000
75%     40.000000  100974.027500
max     40.000000  119971.650000

In [25]:
print("Minimum Age:", df["Age"].min())
print("Maximum Age:", df["Age"].max())

print("Minimum Salary:", df["Salary"].min())
print("Maximum Salary:", df["Salary"].max())

Minimum Age: 25.0
Maximum Age: 40.0
Minimum Salary: 50047.32
Maximum Salary: 119971.65

In [ ]:
## 3. Missing Data Handling

### Age

The `Age` column contains missing values. Median imputation will be used because age is a numerical variable and the median is less affected by extreme values than the mean. This helps preserve the available employee records without allowing potential outliers to significantly influence the imputed values.

### Salary

The `Salary` column also contains missing values. Median imputation will be used because salary data can be skewed by employees with unusually high salaries. The median therefore provides a more robust estimate of a typical salary.

### Row Deletion

Rows will not be deleted solely because `Age` or `Salary` is missing. Since only a portion of the dataset contains missing values, imputation allows us to retain useful employee records.

In [26]:
# Store median values before imputation

age_median = df["Age"].median()
salary_median = df["Salary"].median()

print("Age median:", age_median)
print("Salary median:", salary_median)

Age median: 30.0
Salary median: 85547.87

In [27]:
# Fill missing numerical values with median

df["Age"] = df["Age"].fillna(age_median)
df["Salary"] = df["Salary"].fillna(salary_median)

In [28]:
df.isnull().sum()

Employee_ID          0
First_Name           0
Last_Name            0
Age                  0
Department_Region    0
Status               0
Join_Date            0
Salary               0
Email                0
Phone                0
Performance_Score    0
Remote_Work          0
dtype: int64

In [ ]:
## 4. Duplicate Removal

The dataset was checked for exact duplicate rows using Pandas `duplicated()`.

No exact duplicate records were found, so no rows were removed during this step. The duplicate count before and after cleaning will be documented in the final comparison table.

In [29]:
duplicates_before = df.duplicated().sum()

df = df.drop_duplicates()

duplicates_after = df.duplicated().sum()

print("Duplicates before cleaning:", duplicates_before)
print("Duplicates after cleaning:", duplicates_after)

Duplicates before cleaning: 0
Duplicates after cleaning: 0

In [30]:
for col in ["Department_Region", "Status", "Performance_Score"]:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- Department_Region ---
Department_Region
HR-Florida               41
DevOps-California        35
Sales-Nevada             35
Admin-Nevada             34
Admin-California         34
DevOps-Florida           34
Finance-Illinois         33
DevOps-New York          33
Sales-Florida            33
HR-New York              33
DevOps-Illinois          33
Finance-California       32
Sales-California         31
Sales-Illinois           30
Admin-Illinois           29
Finance-Texas            29
Cloud Tech-Texas         29
Cloud Tech-California    29
Finance-Nevada           29
Cloud Tech-Florida       28
DevOps-Nevada            27
DevOps-Texas             27
Sales-New York           26
HR-California            26
Admin-Florida            25
Cloud Tech-New York      24
Finance-Florida          24
HR-Illinois              24
HR-Nevada                24
HR-Texas                 23
Finance-New York         23
Sales-Texas              23
Admin-Texas              22
Admin-New York           22
Cloud Tech-Nevada        20
Cloud Tech-Illinois      16
Name: count, dtype: int64

--- Status ---
Status
Pending     356
Active      352
Inactive    312
Name: count, dtype: int64

--- Performance_Score ---
Performance_Score
Good         270
Average      267
Excellent    267
Poor         216
Name: count, dtype: int64

In [31]:
text_columns = ["Department_Region", "Status", "Performance_Score"]

for col in text_columns:
    df[col] = df[col].astype(str).str.strip()

In [32]:
df["Status"] = (
    df["Status"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.title()
)

In [33]:
df["Status"].value_counts()

Status
Pending     356
Active      352
Inactive    312
Name: count, dtype: int64

In [34]:
print(df["Join_Date"].dtype)

object

In [35]:
df["Join_Date"] = pd.to_datetime(
    df["Join_Date"],
    errors="coerce"
)

In [36]:
print(df["Join_Date"].dtype)

datetime64[ns]

In [37]:
print("Invalid dates:", df["Join_Date"].isnull().sum())

Invalid dates: 0

In [ ]:
### Date Standardisation

The `Join_Date` column was converted from object/string format to Pandas datetime format using `pd.to_datetime()`. Invalid date values were converted to missing values using `errors="coerce"`, allowing them to be identified and handled safely.

In [38]:
df["Phone"] = df["Phone"].astype("string")

In [39]:
print(df["Phone"].dtype)

string

In [ ]:
### Phone Data Type Correction

The `Phone` column was converted from an integer data type to string because phone numbers are identifiers and should not be used for mathematical calculations. Storing them as strings also prevents unintended numerical operations.

In [40]:
df.dtypes

Employee_ID                  object
First_Name                   object
Last_Name                    object
Age                         float64
Department_Region            object
Status                       object
Join_Date            datetime64[ns]
Salary                      float64
Email                        object
Phone                string[python]
Performance_Score            object
Remote_Work                    bool
dtype: object

In [ ]:
## 5. Outlier Detection

The Interquartile Range (IQR) method is used to identify potential outliers in numerical columns.

The lower and upper boundaries are calculated using the first quartile (Q1), third quartile (Q3), and IQR. Observations outside these boundaries are considered potential outliers.

Outliers will not automatically be deleted because an extreme value may represent a genuine employee record. The detected observations will therefore be reviewed before deciding whether to retain, cap, or remove them.

In [41]:
numeric_columns = ["Age", "Salary"]

outlier_summary = []

for col in numeric_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = df[
        (df[col] < lower_bound) |
        (df[col] > upper_bound)
    ]
    
    outlier_summary.append({
        "Column": col,
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "Lower Bound": lower_bound,
        "Upper Bound": upper_bound,
        "Outlier Count": len(outliers)
    })

outlier_summary = pd.DataFrame(outlier_summary)

outlier_summary

,Column,Q1,Q3,IQR,Lower Bound,Upper Bound,Outlier Count
0,Age,30.0000,35.0000,5.00,22.5000,42.5000,0
1,Salary,68811.2325,100372.6625,31561.43,21469.0875,147714.8075,0

In [46]:
Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

salary_outliers = df[
    (df["Salary"] < lower) |
    (df["Salary"] > upper)
]

salary_outliers[["Employee_ID", "Salary"]]

Empty DataFrame
Columns: [Employee_ID, Salary]
Index: []

In [47]:
print("Minimum age:", df["Age"].min())
print("Maximum age:", df["Age"].max())

Minimum age: 25.0
Maximum age: 40.0

In [ ]:
## 6. Final Data Validation

After completing the cleaning process, the dataset is validated to ensure that missing values, duplicate records, inconsistent data types, and formatting issues have been addressed.

The final dataset should be complete, consistent, and suitable for further analysis.

In [49]:
print("Total missing values:", df.isnull().sum().sum())
print("Total duplicate rows:", df.duplicated().sum())
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

Total missing values: 0
Total duplicate rows: 0
Number of rows: 1020
Number of columns: 12

In [50]:
df.isnull().sum()

Employee_ID          0
First_Name           0
Last_Name            0
Age                  0
Department_Region    0
Status               0
Join_Date            0
Salary               0
Email                0
Phone                0
Performance_Score    0
Remote_Work          0
dtype: int64

In [51]:
dtype_report = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str).values
})

dtype_report

               Column       Data Type
0         Employee_ID          object
1          First_Name          object
2           Last_Name          object
3                 Age         float64
4   Department_Region          object
5              Status          object
6           Join_Date  datetime64[ns]
7              Salary         float64
8               Email          object
9               Phone          string
10  Performance_Score          object
11        Remote_Work            bool

In [52]:
before_rows
before_columns
before_nulls
before_duplicates

np.int64(0)

In [53]:
after_rows = len(df)
after_columns = len(df.columns)
after_nulls = df.isnull().sum().sum()
after_duplicates = df.duplicated().sum()

In [54]:
comparison = pd.DataFrame({
    "Metric": [
        "Row Count",
        "Column Count",
        "Missing Values",
        "Duplicate Rows"
    ],
    "Before Cleaning": [
        before_rows,
        before_columns,
        before_nulls,
        before_duplicates
    ],
    "After Cleaning": [
        after_rows,
        after_columns,
        after_nulls,
        after_duplicates
    ]
})

comparison

           Metric  Before Cleaning  After Cleaning
0       Row Count             1020            1020
1    Column Count               12              12
2  Missing Values              235               0
3  Duplicate Rows                0               0

In [ ]:
### Outlier Summary

The IQR method was used to detect potential outliers in numerical columns such as Age and Salary. Potential outliers were reviewed rather than automatically removed because extreme employee values may represent valid business observations.

Legitimate observations were retained to avoid unnecessary data loss.

In [55]:
outlier_summary

,Column,Q1,Q3,IQR,Lower Bound,Upper Bound,Outlier Count
0,Age,30.0000,35.0000,5.00,22.5000,42.5000,0
1,Salary,68811.2325,100372.6625,31561.43,21469.0875,147714.8075,0

In [56]:
df.head(10)

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,2021-04-02,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,30.0,Finance-Texas,Active,2020-07-10,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,30.0,Admin-Nevada,Pending,2023-12-07,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,2021-11-27,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,2022-01-05,109324.61,frank.williams@example.com,-1586734256,Poor,False
5,EMP1005,Alice,Garcia,40.0,Sales-Texas,Inactive,2020-06-10,88642.84,alice.garcia@example.com,-5409003485,Good,False
6,EMP1006,Frank,Jones,30.0,Admin-Nevada,Active,2020-04-03,96288.43,frank.jones@example.com,-4518376063,Good,False
7,EMP1007,Bob,Jones,30.0,Cloud Tech-Florida,Inactive,2022-07-17,94497.91,bob.jones@example.com,-4134327559,Average,True
8,EMP1008,Frank,Davis,35.0,Admin-Nevada,Inactive,2023-12-08,115565.82,frank.davis@example.com,-4177656123,Excellent,True
9,EMP1009,Charlie,Johnson,30.0,DevOps-New York,Active,2022-08-04,76561.88,charlie.johnson@example.com,-8156985699,Excellent,True

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                1020 non-null   float64
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   datetime64[ns]
 7   Salary             1020 non-null   float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   string
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), datetime64[ns](1), float64(2), object(7), string(1)
memory usage: 88.8+ KB

In [58]:
df.to_csv("cleaned_employee_dataset.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [59]:
cleaned_df = pd.read_csv("cleaned_employee_dataset.csv")

print("Rows:", cleaned_df.shape[0])
print("Columns:", cleaned_df.shape[1])

Rows: 1020
Columns: 12

In [60]:
cleaned_df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,2021-04-02,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,30.0,Finance-Texas,Active,2020-07-10,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,30.0,Admin-Nevada,Pending,2023-12-07,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,2021-11-27,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,2022-01-05,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [61]:
comparison

           Metric  Before Cleaning  After Cleaning
0       Row Count             1020            1020
1    Column Count               12              12
2  Missing Values              235               0
3  Duplicate Rows                0               0

In [62]:
outlier_summary

,Column,Q1,Q3,IQR,Lower Bound,Upper Bound,Outlier Count
0,Age,30.0000,35.0000,5.00,22.5000,42.5000,0
1,Salary,68811.2325,100372.6625,31561.43,21469.0875,147714.8075,0

In [63]:
df.dtypes

Employee_ID                  object
First_Name                   object
Last_Name                    object
Age                         float64
Department_Region            object
Status                       object
Join_Date            datetime64[ns]
Salary                      float64
Email                        object
Phone                string[python]
Performance_Score            object
Remote_Work                    bool
dtype: object

In [ ]:
## 7. Before vs. After Cleaning Summary

The following table compares the dataset before and after the cleaning process. It summarizes the changes in row count, missing values, duplicate records, and outlier observations.

In [ ]:
# Conclusion

The messy employee dataset was successfully transformed into a clean and analysis-ready dataset using Python, Pandas, and NumPy.

The project covered the complete data cleaning workflow, including data quality assessment, missing value treatment, duplicate verification, data standardisation, date conversion, data type correction, and IQR-based outlier detection.

A total of 235 missing values were identified initially and successfully handled using appropriate imputation techniques. No duplicate rows were found. The `Join_Date` column was converted to datetime format, while the `Phone` column was converted to string format because phone numbers are identifiers rather than numerical values.

The IQR method identified no outliers in the Age or Salary columns, so no observations were removed or capped. The dataset retained all 1,020 original records.

The final cleaned dataset was exported as `cleaned_employee_dataset.csv` and is ready for further analysis and reporting.